/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project2.mybudget.views;

import com.project2.mybudget.App;
import com.project2.mybudget.controllers.AccountsController;
import com.project2.mybudget.data.Mailing;
import com.project2.mybudget.exception.AppException;
import com.project2.mybudget.exception.ExceptionViewer;
import com.project2.mybudget.models.Account;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Giang
 */
public class AccountConfirmation extends javax.swing.JFrame {

    private final ConfirmationType type;
    private StringBuilder emailMessage;
    private String code;
    private String email;
    private String emailTitle;

    public static enum ConfirmationType {
        CONFIRM, RECOVERY
    }

    /**
     * Creates new form AccountConfirmation
     *
     * @param type
     * @param code
     * @param email
     */
    public AccountConfirmation(ConfirmationType type, String code, String email) {
        initComponents();
        setIconImage(App.ICON);
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        
        emailMessage = new StringBuilder();
        this.type = type;
        this.code = code;
        this.email = email;

        btnConfirm.setEnabled(false);
        btnResend.setEnabled(false);

        initText();
    }

    private void initText() {
        emailTitle = "";
        switch (type) {
            case CONFIRM:
                lblTitle.setText("Account confirmation");
                lblInfo.setText("To complete account creation,");
                lblInfo1.setText("please check your provided email to get confirmation code.");
                emailTitle = "Account register confirmation - MyBudget";
                emailMessage.append("Hello user,<br/>To validate your email address, please enter ")
                        .append("the folowing <b>Confirmation code<b/> to complete account regisration.")
                        .append("<br/><br/>Here's your code:<br/><h2>").append(code).append("</h2>")
                        .append("<br/><br/>If you didn't register MyBudget account or acquire confirmation code, ")
                        .append("please ignore this email.<br/><i>Thank you!</i>");
                break;
            case RECOVERY:
                lblTitle.setText("Password recovery");
                lblInfo.setText("An email with confirmation code has been sent to ");
                lblInfo1.setText("your account email, please check your email for code.");
                emailTitle = "Password recovery - MyBudget";
                emailMessage.append("Hello user,<br/>To reset your password, please enter ")
                        .append("the folowing <b>Confirmation code<b/> to get your new password.")
                        .append("<br/><br/>Here's your code:<br/><h2>").append(code).append("</h2>")
                        .append("<br/><br/>If you didn't acquire confirmation code, ")
                        .append("please ignore this email.<br/><i>Thank you!</i>");
                break;
        }
        new Mailing(email, emailTitle, emailMessage.toString()).start();

        //resetCountdown();
        btnResend.setVisible(false);
    }

    private void resetCountdown() {
        btnResend.setEnabled(false);
        for (int i = 120; i > 0; i--) {
            btnResend.setText("please wait " + i + "s");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                // ignore
            }
        }
        btnResend.setText("Resend code");
        btnResend.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnResend = new javax.swing.JButton();
        lblInfo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyBudget Account Confirmation");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("<title>");
        lblTitle.setToolTipText("");

        lblInfo.setText("<information text>");

        jLabel1.setText("Confirmation code:");

        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodeKeyReleased(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnResend.setText("Resend code");
        btnResend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResendActionPerformed(evt);
            }
        });

        lblInfo1.setText("<information text 1>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnResend)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCode))
                    .addComponent(lblInfo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResend)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyReleased
        if (txtCode.getText().length() == code.length()) {
            btnConfirm.setEnabled(true);
        } else {
            btnConfirm.setEnabled(false);
        }
    }//GEN-LAST:event_txtCodeKeyReleased

    private void btnResendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResendActionPerformed
        new Mailing(email, emailTitle, emailMessage.toString()).start();
        resetCountdown();
    }//GEN-LAST:event_btnResendActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        if (txtCode.getText().toUpperCase().equals(code.toUpperCase())) {
            switch (type) {
                case CONFIRM:
                    Account.Info info = App.ACCOUNT.getAccount().getInfo();
                    info.status = 1;
                    App.ACCOUNT.getAccount().setInfo(info);
                     {
                        try {
                            App.ACCOUNT.updateInfo();
                            JOptionPane.showMessageDialog(null, "You have confirmed your account.\nNow you can access MyBudget, enjoy!", "Confirmation completed", JOptionPane.INFORMATION_MESSAGE);
                            MainScreen.run();
                            this.dispose();
                        } catch (AppException ex) {
                            ExceptionViewer.view(ex);
                        }
                    }
                    break;
                case RECOVERY: {
                    try {
                        App.ACCOUNT.recoverPassword(email);
                        JOptionPane.showMessageDialog(null, "Your new password:\n 12345678", "New password", JOptionPane.INFORMATION_MESSAGE);
                        AccountLogin.run();
                        this.dispose();
                    } catch (AppException ex) {
                        ExceptionViewer.view(ex);
                    }
                }
                break;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Wrong confirmation code. Please check again!", "Confiramtion failed", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void run(ConfirmationType type, String code, String email) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(new WindowsLookAndFeel());
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountConfirmation(type, code, email).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnResend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
